# -*- coding: utf-8 -*-
"""SemanticKernel_SkillComposition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WfXG31CDFCxpMUSTEOSTM23RiUVSRgF
"""

!pip install semantic-kernel google-generativeai -q

import google.generativeai as genai
import semantic_kernel as sk
from semantic_kernel.functions.kernel_plugin import KernelPlugin
from semantic_kernel.functions import kernel_function
import asyncio

API_KEY = "AIzaSyDvmXzyjXOHipKFddCzIUXpCWBFIb68fH0"  # replace with your key
genai.configure(api_key=API_KEY)
model_name = "gemini-2.5-flash"

kernel = sk.Kernel()

@kernel_function(
    description="Summarizes a given text using Gemini 2.5 Flash",
    name="Summarize",
)
def summarize_text(text: str) -> str:
    model = genai.GenerativeModel(model_name)
    response = model.generate_content(f"Summarize this in one concise paragraph:\n{text}")
    return response.text.strip()

summarization_plugin = KernelPlugin(
    name="SummarizationPlugin", description="Summarizes text using Gemini"
)
kernel.add_plugin(summarization_plugin)
kernel.add_function(plugin_name="SummarizationPlugin", function=summarize_text)

@kernel_function(
    description="Analyzes the sentiment of text",
    name="AnalyzeSentiment",
)
def sentiment_score(text: str) -> str:
    positive = ["good", "great", "excellent", "amazing", "positive"]
    negative = ["bad", "poor", "terrible", "negative", "worst"]

    pos = sum(word in text.lower() for word in positive)
    neg = sum(word in text.lower() for word in negative)

    if pos > neg:
        return "😊 Positive sentiment"
    elif neg > pos:
        return "😞 Negative sentiment"
    else:
        return "😐 Neutral sentiment"

sentiment_plugin = KernelPlugin(
    name="SentimentSkill", description="Analyzes sentiment"
)
kernel.add_plugin(sentiment_plugin)
kernel.add_function(plugin_name="SentimentSkill", function=sentiment_score)

async def composed_skill(input_text: str):
    summary = summarize_text(input_text)
    print("\n🔹 Summary:\n", summary)

    sentiment = sentiment_score(summary)
    print("\n🔹 Sentiment:\n", sentiment)

input_text = """
I recently tried the new restaurant downtown. The food was excellent,
and the service was great. The ambiance made me feel very comfortable.
However, the waiting time was a bit long, but overall it was a good experience.
"""

await composed_skill(input_text)