# -*- coding: utf-8 -*-
"""prompt_comparison_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuAt1VRw2rlOnOwcgMArI2Ql7aCVOKKi
"""

!pip install boto3

#!/usr/bin/env python3
"""
prompt_comparison_pipeline.py

Compare multiple prompt patterns using AWS Bedrock Claude 3 Sonnet.
Print outputs side by side and provide simple quality scoring.
"""

import boto3
import json

# ---------------- AWS Bedrock direct credentials ----------------
AWS_ACCESS_KEY = "AKIAVSX4Z23PH4R4CRWQ"
AWS_SECRET_KEY = "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"
AWS_REGION = "us-east-1"
MODEL_ID = "anthropic.claude-3-sonnet-20240229-v1:0"

# ---------------- Prompt variations ----------------
prompt_variations = [
    {
        "name": "concise_zero_shot",
        "prompt": "Write Python function factorial(n:int)->int. Raise ValueError if n<0."
    },
    {
        "name": "detailed_zero_shot",
        "prompt": "You are a Python developer. Implement factorial(n:int)->int. Include docstring, type hints, minimal comments. Raise ValueError if input < 0."
    },
    {
        "name": "few_shot",
        "prompt": """You are a professional Python developer. Example:

Spec: add(a:int, b:int) -> int that returns a+b
Code:
def add(a:int,b:int)->int:
    \"\"\"Return sum of a and b\"\"\"
    return a + b

Now implement factorial(n:int)->int. Raise ValueError if n<0.
"""
    }
]

# ---------------- Invoke Bedrock model ----------------
rt = boto3.client(
    "bedrock-runtime",
    region_name=AWS_REGION,
    aws_access_key_id=AWS_ACCESS_KEY,
    aws_secret_access_key=AWS_SECRET_KEY
)

# ---------------- Run variations ----------------
outputs = []

for var in prompt_variations:
    print(f"\n=== Running Variation: {var['name']} ===\n")
    print("Prompt:\n", var["prompt"])

    body = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 500,
        "temperature": 0.2,
        "messages": [{"role": "user", "content": var["prompt"]}]
    }

    response = rt.invoke_model(
        modelId=MODEL_ID,
        body=json.dumps(body),
        contentType="application/json"
    )

    obj = json.loads(response["body"].read())
    text = obj["content"][0]["text"].strip()

    # Remove code fences if present
    if text.startswith("```"):
        text = text.strip("```").strip()

    # Append output for comparison
    outputs.append({
        "variation": var["name"],
        "prompt": var["prompt"],
        "output": text
    })

# ---------------- Compare outputs ----------------
print("\n\n=== Comparison of Prompt Variations ===\n")

for o in outputs:
    print(f"--- Variation: {o['variation']} ---")
    print("Generated Output:\n", o["output"])

    # Simple quality scoring
    score = 0
    if "def factorial" in o["output"]:
        score += 1
    if "raise ValueError" in o["output"]:
        score += 1
    if "\"\"\"" in o["output"] or "# " in o["output"]:
        score += 1
    print(f"Simple Quality Score (0-3): {score}/3")
    print("\n-----------------------------\n")