# -*- coding: utf-8 -*-
"""ner_sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btfBDYtqrZaScZsidHWPdp9ZbBjWmbs9
"""

# Cell 1 — Install libraries and download models/corpora (run once)
!pip install -U spacy textblob
!python -m spacy download en_core_web_sm
!python -m textblob.download_corpora

# Cell 2 — Imports and load spaCy model
import spacy
from textblob import TextBlob

nlp = spacy.load("en_core_web_sm")

# Optional Cell — Download NLTK punkt if you see tokenizer errors
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

# Cell 3 — Text, Named Entity Recognition (NER) and Sentiment with TextBlob
text = "Amazon is acquiring a startup in San Francisco for $1 billion. I am excited about this news!"

# --- NER ---
doc = nlp(text)
print("\n=== Named Entities ===")
for ent in doc.ents:
    print(f"Text: {ent.text}, Label: {ent.label_}")

# --- Sentiment ---
blob = TextBlob(text)
print("\n=== Sentiment ===")
print("Polarity:", blob.sentiment.polarity)
print("Subjectivity:", blob.sentiment.subjectivity)

