# -*- coding: utf-8 -*-
"""Concurrency_StepCounter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11oiTWryZ3cDgY6QtbE-8BJh8KQ627TdZ
"""

!pip install -q google-generativeai
import google.generativeai as genai

genai.configure(api_key="AIzaSyDvmXzyjXOHipKFddCzIUXpCWBFIb68fH0")

shared_memory = {
    "step_counter": 0,
    "max_steps": 5,
    "lock": None
}

def acquire_lock(agent_name):
    if shared_memory["lock"] is None:
        shared_memory["lock"] = agent_name
        return True
    return False

def release_lock(agent_name):
    if shared_memory["lock"] == agent_name:
        shared_memory["lock"] = None

def agent(agent_name):
    if not acquire_lock(agent_name):
        print(f"🔒 {agent_name} could not acquire lock. Skipping this cycle.")
        return

    current_step = shared_memory["step_counter"]
    if current_step >= shared_memory["max_steps"]:
        print(f"✅ {agent_name}: All steps completed.")
        release_lock(agent_name)
        return

    model = genai.GenerativeModel("gemini-2.5-flash")
    prompt = f"{agent_name} is executing step {current_step}. Describe what happens at this step."
    response = model.generate_content(prompt)

    print(f"\n🧠 {agent_name} executed step {current_step}:\n➡️ {response.text}")

    shared_memory["step_counter"] += 1
    release_lock(agent_name)

for i in range(10):
    print(f"\n--- Cycle {i+1} ---")

    # Reset lock before each cycle to simulate concurrency
    shared_memory["lock"] = None

    agent("Summarizer")
    agent("Analyst")









