# -*- coding: utf-8 -*-
"""Search and summarization tools for agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGjDWI3qHiOFAZhNq32miCQf5ULW7VZ7
"""

!pip install langchain langchain_google_genai langchain_community duckduckgo-search
!pip install -U ddgs

import os
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.tools import DuckDuckGoSearchResults
from langchain.tools import Tool
from langchain.agents import initialize_agent, AgentType

# ============================================================
# 🔐 Step 1: Authenticate Gemini using API key
# ============================================================
# Get your Gemini API key from https://aistudio.google.com/app/apikey
os.environ["GOOGLE_API_KEY"] = "AIzaSyAcjOor3UwW4YK3EEJ3cx4BwqmtFdJ1vwc"

# 🤖 Step 2: Initialize Gemini 2.5 Flash Model
# ============================================================
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.3)

# ============================================================
# 🌐 Step 3: Define Search Tool (DuckDuckGo)
# ============================================================
search_tool = DuckDuckGoSearchResults(name="Web Search")

def summarize_text(query: str) -> str:
    """Summarize text or search results using Gemini."""
    prompt = f"Summarize the following text into 5 short, clear bullet points:\n\n{query}"
    response = llm.invoke(prompt)
    return response.content if hasattr(response, "content") else str(response)

summarize_tool = Tool(
    name="Summarizer",
    func=summarize_text,
    description="Summarizes text or content using Gemini model."
)

# 🧩 Step 5: Create an Agent with Both Tools
# ============================================================
tools = [search_tool, summarize_tool]
agent = initialize_agent(
    tools,
    llm,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True
)

query = "Summarize the latest advancements in Generative AI"
response = agent.run(query)

print("\n✅ FINAL SUMMARY:\n", response)

