# -*- coding: utf-8 -*-
"""Memory across agent roles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uqP9oRv8nyb275taG4IgRzKsrvxnprfH
"""

# Install AWS SDK
!pip install boto3 --quiet

import boto3
import json
import time

# ---------------------------
# CONFIG: Enter your details
# ---------------------------
aws_access_key_id = "AKIAVSX4Z23PIAV77M44"
aws_secret_access_key = "q9xwDi7rfRQCMk5scwbunDkRJfUVddyeVVoW0K1K"
region_name = "us-east-1"  # e.g., 'us-east-1'
bucket_name = "agent-shared-memory"  # your bucket name
state_file = "agent_state.json"  # shared state file

# ---------------------------
# Connect to S3
# ---------------------------
s3 = boto3.client(
    "s3",
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
    region_name=region_name
)

# ---------------------------
# Functions to Read/Write State
# ---------------------------
def read_state():
    try:
        obj = s3.get_object(Bucket=bucket_name, Key=state_file)
        state = json.loads(obj['Body'].read().decode())
        return state
    except s3.exceptions.NoSuchKey:
        return {}  # if state file doesn't exist yet

def write_state(state):
    s3.put_object(
        Bucket=bucket_name,
        Key=state_file,
        Body=json.dumps(state)
    )
    print("State updated!")

def safe_write_state(new_data, retries=3):
    """Safely merge new data to existing state"""
    for _ in range(retries):
        state = read_state()
        state.update(new_data)
        try:
            write_state(state)
            return
        except Exception as e:
            print("Retrying...", e)
            time.sleep(0.5)

# ---------------------------
# SIMULATION: Two Agents
# ---------------------------
# Agent A writes something
safe_write_state({'agent_a': "Hello from Agent A"})

# Agent B reads and writes
state = read_state()
print("Agent B sees:", state)
safe_write_state({'agent_b': "Hello from Agent B"})

# Agent A reads final state
state = read_state()
print("Final shared state:", state)

