# -*- coding: utf-8 -*-
"""prompt_variation_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mA7kn56g3hak3C0T65XXE8v2ngXH-Sv
"""

!pip install boto3

#!/usr/bin/env python3
"""
prompt_variation_pipeline.py

Run multiple prompt variations on a task using AWS Bedrock (Claude 3 Sonnet)
without Docker or aws configure. Performs basic syntax checks.
"""

import boto3
import json

# ---------------- AWS Bedrock direct credentials ----------------
AWS_ACCESS_KEY = "AKIAVSX4Z23PH4R4CRWQ"
AWS_SECRET_KEY = "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"
AWS_REGION = "us-east-1"  # region where Claude 3 Sonnet is available
MODEL_ID = "anthropic.claude-3-sonnet-20240229-v1:0"

# ---------------- Prompt variations ----------------
prompt_variations = [
    {
        "name": "concise_zero_shot",
        "prompt": "Write Python function factorial(n:int)->int. Raise ValueError if n<0.",
        "temperature": 0
    },
    {
        "name": "detailed_zero_shot",
        "prompt": "You are a Python developer. Implement factorial(n:int)->int. Include docstring, type hints, and minimal comments. Raise ValueError if input < 0.",
        "temperature": 0
    },
    {
        "name": "few_shot",
        "prompt": """You are a professional Python developer. Here is an example:

Spec: add(a:int, b:int) -> int that returns a+b
Code:
def add(a:int,b:int)->int:
    \"\"\"Return sum of a and b\"\"\"
    return a + b

Now implement factorial(n:int)->int. Raise ValueError if n<0.
""",
        "temperature": 0
    }
]

# ---------------- Function to invoke Bedrock model ----------------
def invoke_model(prompt: str, temperature: float = 0.2) -> str:
    rt = boto3.client(
        "bedrock-runtime",
        region_name=AWS_REGION,
        aws_access_key_id=AWS_ACCESS_KEY,
        aws_secret_access_key=AWS_SECRET_KEY
    )
    body = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 500,
        "temperature": temperature,
        "messages": [{"role": "user", "content": prompt}]
    }
    resp = rt.invoke_model(
        modelId=MODEL_ID,
        body=json.dumps(body),
        contentType="application/json"
    )
    obj = json.loads(resp["body"].read())
    if "content" in obj and len(obj["content"]) > 0:
        return obj["content"][0].get("text", "").strip()
    return ""

# ---------------- Basic syntax check ----------------
def check_syntax(code_text: str) -> bool:
    """
    Returns True if the code compiles (basic Python syntax check), else False
    """
    try:
        compile(code_text, "<string>", "exec")
        return True
    except Exception as e:
        print(f"Syntax Error: {e}")
        return False

# ---------------- Run prompt variations ----------------
def run_variations():
    results = []
    for var in prompt_variations:
        print(f"\n=== Running Variation: {var['name']} ===")
        output = invoke_model(var['prompt'], temperature=var['temperature'])
        # remove ``` if model returned code block
        if output.startswith("```"):
            output = output.strip("```").strip()
        print("Generated Code:\n", output)
        syntax_ok = check_syntax(output)
        print("Syntax check:", "PASS" if syntax_ok else "FAIL")
        results.append({
            "variation": var['name'],
            "prompt": var['prompt'],
            "output": output,
            "syntax_ok": syntax_ok
        })
    return results

# ---------------- Main ----------------
if __name__ == "__main__":
    run_variations()