# -*- coding: utf-8 -*-
"""RAG_Chunking_VectorSearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JVLrE7upj-u7UnUEMjdToQNVscyHjbu
"""

import nltk

nltk.download('punkt')

nltk.download('punkt_tab')

!pip install streamlit langchain faiss-cpu pypdf google-generativeai sentence-transformers

# Install required packages

!pip install -q google-genai sentence-transformers faiss-cpu pypdf nltk

#Imports

import os

import numpy as np

from typing import List, Dict, Any

import nltk

nltk.download('punkt')

from sentence_transformers import SentenceTransformer

import faiss

from pypdf import PdfReader

# 1) Configure Gemini
# ------------------------------
GEMINI_API_KEY = os.environ.get("GOOGLE_API_KEY")
if not GEMINI_API_KEY:
    GEMINI_API_KEY = input("Enter your Gemini API key: ").strip()
os.environ["GOOGLE_API_KEY"] = GEMINI_API_KEY
from google import genai
client = genai.Client(api_key=GEMINI_API_KEY)
GEMINI_MODEL = "gemini-2.5-flash"  # Adjust to your available model

#2) Upload PDF and extract text
 # ------------------------------
from google.colab import files
 print("Upload your PDF file:")
 uploaded = files.upload()
 if not uploaded:
    raise SystemExit("No PDF uploaded.")
 pdf_file = list(uploaded.keys())[0]
 reader = PdfReader(pdf_file)
 raw_text = ""
 for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        raw_text += page_text + "\n"
 print(f"PDF loaded: {pdf_file}, {len(raw_text)} characters extracted.")

# 3) Chunking function
# ------------------------------
def chunk_text(text: str, max_words: int = 200, overlap_words: int = 40) -> List[Dict[str,Any]]:
    sentences = nltk.tokenize.sent_tokenize(text)
    chunks = []
    current = []
    current_len = 0
    idx = 0
    for sent in sentences:
        words = sent.split()
        if current_len + len(words) <= max_words:
            current.append(sent)
            current_len += len(words)
        else:
            chunk_text_str = " ".join(current).strip()
            if chunk_text_str:
                chunks.append({"id": idx, "text": chunk_text_str})
                idx += 1
            # create overlapping window
            window = []
            wcount = 0
            for s in reversed(current):
                sw = s.split()
                if wcount + len(sw) > overlap_words:
                    break
                window.insert(0, s)
                wcount += len(sw)
            current = window + [sent]
            current_len = sum(len(s.split()) for s in current)
    if current:
        chunks.append({"id": idx, "text": " ".join(current).strip()})
    return chunks

chunks = chunk_text(raw_text, max_words=220, overlap_words=50)
print(f"Created {len(chunks)} chunks.")

#4) Create embeddings
 # ------------------------------
embed_model = SentenceTransformer("all-MiniLM-L6-v2")
texts = [c["text"] for c in chunks]
embs = embed_model.encode(texts, show_progress_bar=True, convert_to_numpy=True)
emb_dim = embs.shape[1]

# 5) Build FAISS index
# ------------------------------
faiss.normalize_L2(embs)
index = faiss.IndexFlatIP(emb_dim)
index.add(embs)
print("FAISS index built with", index.ntotal, "vectors.")

# 6) Retrieval function
 # ------------------------------
def retrieve(query: str, top_k: int = 5) -> List[Dict[str,Any]]:
    q_emb = embed_model.encode([query], convert_to_numpy=True)
    faiss.normalize_L2(q_emb)
    D, I = index.search(q_emb, top_k)
    results = []
    for idx, score in zip(I[0], D[0]):
        if idx < 0:
            continue
        results.append({"id": int(idx), "score": float(score), "text": chunks[idx]["text"]})
    return results

# 7) LLM query using updated Gemini API
 # ------------------------------
def call_gemini(prompt: str) -> str:
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt
    )
    return response.text.strip()

def answer_query_with_context(query: str, top_k: int = 5) -> Dict[str,Any]:
    retrieved = retrieve(query, top_k=top_k)
    context_texts = [f"[doc_id:{r['id']} | score:{r['score']:.4f}]\n{r['text']}" for r in retrieved]
    prompt = f"""
 You are a helpful assistant. Use only the context below to answer the question. If context does not contain the answer, say 'I
  CONTEXT:
 {"\n---\n".join(context_texts)}
 QUESTION:
 {query}
 Answer concisely and cite doc_id(s) used in the answer.
 """
    answer = call_gemini(prompt)
    return {"query": query, "answer": answer, "retrieved": retrieved, "prompt_used": prompt}

# 8) Example usage
# ------------------------------
query = " Explain the steps in the indexing process in a RAG pipeline. "
res = answer_query_with_context(query, top_k=3)
print("\nQuery:", query)
print("LLM Answer:", res["answer"])
print("Retrieved docs:", [(r["id"], r["score"]) for r in res["retrieved"]])