# -*- coding: utf-8 -*-
"""Iphone_Crewai_Usecase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GopAT7IbIVyRyjKazSrCnS-8HJ6fcTm
"""

!pip install -U crewai google-generativeai

from crewai import LLM

llm = LLM(
    model="gemini/gemini-2.5-flash",  # LiteLLM-compatible format
    api_key="AIzaSyDKS1N07Z91j2Ig4uG5hLChvafBC6SKWTQ"
)

from crewai import Agent

summary_agent = Agent(
    role="Product Summarizer",
    goal="Summarize the product features.",
    backstory="Expert in product analysis.",
    llm=llm,
    verbose=True
)

sentiment_agent = Agent(
    role="Review Analyst",
    goal="Analyze customer reviews and extract sentiment insights.",
    backstory="Specialist in understanding customer feedback.",
    llm=llm,
    verbose=True
)

decision_agent = Agent(
    role="Purchase Advisor",
    goal="Make a recommendation on whether to buy the product.",
    backstory="Expert in consumer decision-making.",
    llm=llm,
    verbose=True
)

from crewai import Task

summarize_task = Task(
    description="Summarize the product: {product_query}",
    expected_output="A detailed summary of the product's features, pros, and cons.",
    agent=summary_agent
)

sentiment_task = Task(
    description="Analyze the sentiment of these reviews: {review_text}",
    expected_output="A sentiment summary of the reviews.",
    agent=sentiment_agent
)

decision_task = Task(
    description="Make a YES or NO decision on whether to buy the product, based on the product summary and sentiment analysis from the previous tasks.",
    expected_output="A definitive YES or NO recommendation to buy the product, with a brief justification based on the provided summary and sentiment.",
    agent=decision_agent,
    context=[summarize_task, sentiment_task]
)

from crewai import Crew

crew = Crew(
    agents=[summary_agent, sentiment_agent, decision_agent],
    tasks=[summarize_task, sentiment_task, decision_task] # Ensure tasks are in logical order
)

# Input data
product_query = "iPhone 15"
review_text = "Battery life is great, camera is excellent, but it's a bit expensive. Some users say it's worth it, others prefer Android."

# Run the crew - Agents will use their LLMs based on task descriptions and context
result = crew.kickoff({
    "product_query": product_query,
    "review_text": review_text,
})

print("\n--- Final Decision ---\n")
print(result)