# -*- coding: utf-8 -*-
"""Fallback and retry-enabled LangGraph state graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cjtMA2vT-9wDDTMMSTK9Ui7JZZDE_Hy
"""

!pip install -U langgraph google-generativeai graphviz --quiet
!apt-get install graphviz -y

from langgraph.graph import StateGraph, START, END
import google.generativeai as genai
from graphviz import Digraph
from pydantic import BaseModel
from typing import Optional

genai.configure(api_key="AIzaSyAcjOor3UwW4YK3EEJ3cx4BwqmtFdJ1vwc")

class ReviewState(BaseModel):
    review: str
    ANALYZE_SENTIMENT: Optional[str] = None
    SUMMARIZE: Optional[str] = None
    RECOMMENDATION: Optional[str] = None

def analyze_sentiment(data: ReviewState, attempt=0):
    try:
        response = genai.generate_text(
            model="text-bison-001",
            prompt=f"Analyze sentiment of this review: {data.review}. Is it Positive or Negative?",
            temperature=0.7
        )
        return {"ANALYZE_SENTIMENT": response.text.strip()}
    except Exception:
        if attempt < 2:
            return analyze_sentiment(data, attempt + 1)
        else:
            return {"ANALYZE_SENTIMENT": "Neutral"}

def summarize_review(data: ReviewState, attempt=0):
    try:
        response = genai.generate_text(
            model="text-bison-001",
            prompt=f"Summarize this review: {data.review}",
            temperature=0.7
        )
        return {"SUMMARIZE": response.text.strip()}
    except Exception:
        if attempt < 2:
            return summarize_review(data, attempt + 1)
        else:
            return {"SUMMARIZE": "Unable to summarize the review."}

def generate_recommendation(data: ReviewState, attempt=0):
    if data.ANALYZE_SENTIMENT == "Negative":
        try:
            prompt = f"Review: {data.review}. Suggest improvement recommendations."
            response = genai.generate_text(
                model="text-bison-001",
                prompt=prompt,
                temperature=0.7
            )
            return {"RECOMMENDATION": response.text.strip()}
        except Exception:
            if attempt < 2:
                return generate_recommendation(data, attempt + 1)
            else:
                return {"RECOMMENDATION": "Unable to provide recommendation."}
    else:
        return {"RECOMMENDATION": "No recommendation needed."}

graph = StateGraph(state_schema=ReviewState)
graph.add_node("ANALYZE_SENTIMENT", analyze_sentiment)
graph.add_node("SUMMARIZE", summarize_review)
graph.add_node("RECOMMENDATION", generate_recommendation)

graph.add_edge(START, "ANALYZE_SENTIMENT")
graph.add_edge("ANALYZE_SENTIMENT", "SUMMARIZE")
graph.add_edge("SUMMARIZE", "RECOMMENDATION")
graph.add_edge("RECOMMENDATION", END)

compiled_graph = graph.compile()

from graphviz import Digraph

def visualize_langgraph(graph):
    dot = Digraph(comment="LangGraph")

    # Add nodes
    for node_name in graph.nodes:
        dot.node(node_name, node_name, style="filled", color="lightblue")

    # Add edges
    for edge in graph.edges:
        from_node, to_node = edge  # Only two elements
        dot.edge(from_node, to_node)

    return dot

# Render and display the graph
dot = visualize_langgraph(graph)
dot.render("langgraph", format="png", cleanup=False)
dot  # Display inline in Colab

rreviews = [
    {"review": "Battery life is amazing! I love it."},
    {"review": "Camera quality is poor in low light. Very disappointing."},
    {"review": ""}
]

for r in reviews:
    print("\nInput Review:", r["review"])
    result = compiled_graph.invoke(r)
    print("Graph Output:", result)

