# -*- coding: utf-8 -*-
"""Task_Routing_Logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGjDWI3qHiOFAZhNq32miCQf5ULW7VZ7
"""

!pip install requests langgraph boto3 awscli

!aws configure

from langgraph.graph import StateGraph
from typing import TypedDict, Dict, Any, List
import requests, json, random, time, boto3

# AWS CloudWatch setup for logs
log_group = "/LangGraph/TaskRouting"
log_stream = f"run_{int(time.time())}"
logs_client = boto3.client("logs", region_name="us-east-1")

try:
    logs_client.create_log_group(logGroupName=log_group)
except logs_client.exceptions.ResourceAlreadyExistsException:
    pass
logs_client.create_log_stream(logGroupName=log_group, logStreamName=log_stream)

sequence_token = None
def log(msg: str):
    global sequence_token
    kwargs = {
        "logGroupName": log_group,
        "logStreamName": log_stream,
        "logEvents": [{"timestamp": int(time.time() * 1000), "message": msg}]
    }
    if sequence_token:
        kwargs["sequenceToken"] = sequence_token
    response = logs_client.put_log_events(**kwargs)
    sequence_token = response.get("nextSequenceToken")

# -------------------------
# 1️⃣ Define State Schema
# -------------------------
class GraphState(TypedDict):
    lambda_data: Dict[str, Any]
    task_type: str
    result: str

LAMBDA_API_URL = "https://2ooay23h0c.execute-api.us-east-1.amazonaws.com/default/LangGraphStaticData"

# -------------------------
# 2️⃣ Fetch Data from Lambda
# -------------------------
def fetch_lambda_data(state: GraphState):
    response = requests.get(LAMBDA_API_URL)
    data = response.json()
    if "body" in data:
        data = json.loads(data["body"])
    state["lambda_data"] = data
    # Randomly assign task type to simulate dynamic routing
    state["task_type"] = random.choice(["admin", "user", "moderator"])
    log(f"Fetched data for task type: {state['task_type']}")
    return state

# -------------------------
# 3️⃣ Task-specific Nodes
# -------------------------
def handle_admin_task(state: GraphState):
    users = [u for u in state["lambda_data"]["users"] if u["role"] == "admin"]
    state["result"] = f"Admin tasks completed for {len(users)} users."
    log(state["result"])
    return state

def handle_user_task(state: GraphState):
    users = [u for u in state["lambda_data"]["users"] if u["role"] == "user"]
    state["result"] = f"User tasks completed for {len(users)} users."
    log(state["result"])
    return state

def handle_moderator_task(state: GraphState):
    users = [u for u in state["lambda_data"]["users"] if u["role"] == "moderator"]
    state["result"] = f"Moderator tasks completed for {len(users)} users."
    log(state["result"])
    return state

# -------------------------
# 4️⃣ Routing Function
# -------------------------
def route_tasks(state: GraphState):
    task = state["task_type"]
    if task == "admin":
        return "handle_admin_task"
    elif task == "user":
        return "handle_user_task"
    else:
        return "handle_moderator_task"

# -------------------------
# 5️⃣ Build the Graph
# -------------------------
graph = StateGraph(GraphState)
graph.add_node("fetch_lambda_data", fetch_lambda_data)
graph.add_node("handle_admin_task", handle_admin_task)
graph.add_node("handle_user_task", handle_user_task)
graph.add_node("handle_moderator_task", handle_moderator_task)

graph.add_conditional_edges(
    "fetch_lambda_data",
    route_tasks,
    {
        "handle_admin_task": "handle_admin_task",
        "handle_user_task": "handle_user_task",
        "handle_moderator_task": "handle_moderator_task",
    },
)

graph.set_entry_point("fetch_lambda_data")
compiled_graph = graph.compile()

from concurrent.futures import ThreadPoolExecutor

def run_simulation(i):
    result = compiled_graph.invoke({"lambda_data": {}, "task_type": "", "result": ""})
    print(f"Run {i}: {result['result']}")
    return result["result"]

# Simulate 5 concurrent agent executions
with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(executor.map(run_simulation, range(1, 6)))

print("\nAll simulation results:")
print(results)



















