# -*- coding: utf-8 -*-
"""TwoAssistants_Summarizer_Analyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V17dwstKZRnsH74eiC4vPwQG_K_-8ias
"""

!pip install autogen

from autogen import AssistantAgent, GroupChatManager, GroupChat
from IPython.display import display, Markdown
import time
# Set Gemini API key
import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyDvmXzyjXOHipKFddCzIUXpCWBFIb68fH0"

llm_config = {
    "model": "gemini-2.5-flash",
    "api_key": "AIzaSyDvmXzyjXOHipKFddCzIUXpCWBFIb68fH0",  # Replace with your key
    "api_type": "google"
}

from autogen import AssistantAgent

# Summarizer Agent
summarizer = AssistantAgent(
    name="Summarizer",
    system_message="You are a helpful summarizer. Summarize text concisely.",
    llm_config=llm_config
)

# Analyst Agent
analyst = AssistantAgent(
    name="Analyst",
    system_message="You are an analyst. Analyze text based on the summary and provide insights.",
    llm_config=llm_config
)

def display_box(title, text):
    display(Markdown(f"### {title}\n```\n{text}\n```"))

text_to_process = """
Artificial intelligence is transforming industries. Automation increases productivity,
but also creates new ethical challenges. Companies need to balance efficiency with responsibility.
"""

groupchat = GroupChat(agents=[summarizer, analyst])

groupchat_manager = GroupChatManager(groupchat=groupchat, llm_config=llm_config)
conversation = groupchat_manager.initiate_chat(
    summarizer, # Pass one of the agents from the group as the recipient
    message=text_to_process,
    verbose=True
)

for msg in conversation.chat_history:
    display_box(msg['name'], msg['content'])
    time.sleep(1)