# -*- coding: utf-8 -*-
"""AWS_CloudWatch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASutjvDxSs_0sAvcJvYavrNv0B9Pg0Lv
"""

!pip install boto3 requests langgraph awscli

!aws configure

from langgraph.graph import StateGraph
from typing import TypedDict, Dict, Any
import boto3
import requests
import json
import time

# -------------------------
# 1. CloudWatch Setup
# -------------------------
log_group_name = "/LangGraph/AgentLogs"
log_stream_name = f"agent_run_{int(time.time())}"
logs_client = boto3.client("logs", region_name="us-east-1")

# Create log group if it doesn't exist
try:
    logs_client.create_log_group(logGroupName=log_group_name)
except logs_client.exceptions.ResourceAlreadyExistsException:
    pass

# Create log stream
logs_client.create_log_stream(logGroupName=log_group_name, logStreamName=log_stream_name)

sequence_token = None

def log_to_cloudwatch(message: str):
    global sequence_token
    kwargs = {
        "logGroupName": log_group_name,
        "logStreamName": log_stream_name,
        "logEvents": [
            {"timestamp": int(time.time() * 1000), "message": message}
        ]
    }
    if sequence_token:
        kwargs["sequenceToken"] = sequence_token
    response = logs_client.put_log_events(**kwargs)
    sequence_token = response.get("nextSequenceToken")

# -------------------------
# 2. Define Graph Node
# -------------------------
class GraphState(TypedDict):
    lambda_data: Dict[str, Any]

LAMBDA_API_URL = "https://2ooay23h0c.execute-api.us-east-1.amazonaws.com/default/LangGraphStaticData"

def fetch_lambda_data(state: GraphState):
    try:
        response = requests.get(LAMBDA_API_URL)
        response.raise_for_status()
        data = response.json()

        # Parse JSON safely
        if "body" in data:
            state["lambda_data"] = json.loads(data["body"])
        else:
            state["lambda_data"] = data

        log_to_cloudwatch(f"Fetched Lambda data: {state['lambda_data']}")

    except Exception as e:
        state["lambda_data"] = {"error": str(e)}
        log_to_cloudwatch(f"Error fetching Lambda data: {e}")

    return state

# -------------------------
# 3. Setup LangGraph Agent
# -------------------------
graph = StateGraph(GraphState)
graph.add_node("fetch_lambda_data", fetch_lambda_data)
graph.set_entry_point("fetch_lambda_data")
compiled_graph = graph.compile()

# -------------------------
# 4. Run the Graph
# -------------------------
final_state = compiled_graph.invoke({"lambda_data": {}})
print(final_state["lambda_data"])





