# -*- coding: utf-8 -*-
"""Semantic similarity Titan embeddings via Bedrock..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udnyH-RDmoDkTrNRzG56XF4aRnXJ0puD
"""

!pip install boto3 numpy scikit-learn -q

# ==============================
# 🧠 Titan Embeddings Similarity via Bedrock
# ==============================

# ✅ STEP 1 — Install and Import Dependencies

import boto3
import json
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# ==============================
# ✅ STEP 2 — AWS Credentials Setup
# ==============================
import os

os.environ["AWS_ACCESS_KEY_ID"] = "AKIAVSX4Z23PGE3ZSBWJ"
os.environ["AWS_SECRET_ACCESS_KEY"] = "5bBerfCkFzQVALryrg7OYhQ10QiSd/TVYmNUQiEG"
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"  # or your Bedrock-enabled region

# ==============================
# ✅ STEP 3 — Initialize Bedrock Client
# ==============================
bedrock = boto3.client(service_name="bedrock-runtime", region_name=os.environ["AWS_DEFAULT_REGION"])

def get_titan_embedding(text, model_id="amazon.titan-embed-text-v2:0", dimensions=512, normalize=True):
    """Generate embedding vector for given text using Titan Embeddings."""
    body = {
        "inputText": text,
        "dimensions": dimensions,
        "normalize": normalize
    }
    response = bedrock.invoke_model(
        modelId=model_id,
        body=json.dumps(body),
        accept="application/json",
        contentType="application/json"
    )
    response_body = json.loads(response["body"].read())
    return np.array(response_body["embedding"])

# ==============================
# ✅ STEP 4 — Test Semantic Similarity
# ==============================
query = "How can I get a refund for my ticket?"
documents = [
    "Steps to cancel and refund a booked train ticket.",
    "Procedure for rescheduling my flight to a different date.",
    "Instructions for booking a new hotel reservation online.",
]

print("Generating embeddings... this may take a few seconds ⏳")

query_vec = get_titan_embedding(query)
doc_vecs = [get_titan_embedding(doc) for doc in documents]

# Compute Cosine Similarities
print("\n=== 🔍 Semantic Similarity Results ===\n")
for doc, vec in zip(documents, doc_vecs):
    sim = cosine_similarity(query_vec.reshape(1, -1), vec.reshape(1, -1))[0][0]
    print(f"Document: {doc}\nSimilarity Score: {sim:.4f}\n")





