# -*- coding: utf-8 -*-
"""AWS_Lambda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QwE_DL6sH9msytCbcoPTenMFK7c5MHgu
"""

!pip install langgraph

from langgraph.graph import StateGraph, END
import requests

# Replace with your Lambda API Gateway URL
lambda_url = "https://2ooay23h0c.execute-api.us-east-1.amazonaws.com/default/LangGraphStaticData"

# Send GET request
response = requests.get(lambda_url)

# Check status
if response.status_code == 200:
    data = response.json()
    print("✅ Data received from Lambda:")
    print(data)
else:
    print("❌ Error:", response.status_code, response.text)

from typing import TypedDict, Any
from langgraph.graph import StateGraph, END
import requests

# Define the state schema
class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        lambda_data: Data fetched from the Lambda function.
    """
    lambda_data: Any

# Define the node function to fetch data from Lambda
def fetch_lambda_data(state: GraphState):
    """
    Fetches data from the Lambda API Gateway.

    Args:
        state (GraphState): The current graph state.

    Returns:
        dict: The updated state with fetched data.
    """
    lambda_url = "https://2ooay23h0c.execute-api.us-east-1.amazonaws.com/default/LangGraphStaticData"
    response = requests.get(lambda_url)

    if response.status_code == 200:
        data = response.json()
        print("✅ Data received from Lambda:")
        print(data)
        return {"lambda_data": data}
    else:
        print("❌ Error:", response.status_code, response.text)
        return {"lambda_data": None}


# Create a StateGraph instance with the defined schema
graph = StateGraph(GraphState)

# Add the fetch_lambda_data function as a node
graph.add_node("fetch_lambda_data", fetch_lambda_data)

# Set the entry point to the fetch_lambda_data node
graph.set_entry_point("fetch_lambda_data")

# Add an edge from fetch_lambda_data to END
graph.add_edge("fetch_lambda_data", END)

# Compile the graph
compiled_graph = graph.compile()

# Invoke the graph
final_state = compiled_graph.invoke({"lambda_data": {}})

# Print the fetched Lambda data
print("Final state:", final_state["lambda_data"])