# -*- coding: utf-8 -*-
"""Agent planner roles with CrewAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcRv95EKN41cwFEzcUd_naYs4i-4YQ_r
"""

# Cell 0 — install (run once)
!pip install -U crewai pyyaml google-generativeai --quiet

# Cell 1 — imports and API keys (use getpass so you don't paste keys into the notebook)
from getpass import getpass
import re, yaml, json
from pprint import pprint

# CrewAI imports
from crewai import LLM, Agent, Task, Crew, Process

# get API keys (prompt without echo)
print("If you use Google Gemini for agents, enter GOOGLE_API_KEY; otherwise press Enter.")
GOOGLE_API_KEY = getpass("GOOGLE_API_KEY (Gemini, optional): ")
print("If you will use CrewAI planning=True (default planner), you may need an OpenAI key.")
OPENAI_API_KEY = getpass("OPENAI_API_KEY (for built-in planner, optional): ")
# set environment if needed (some LLM adapters check env vars)
import os
if GOOGLE_API_KEY:
    os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY
if OPENAI_API_KEY:
    os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

# Cell 2 — helpers
def extract_yaml_from_text(text: str) -> str | None:
    """
    Tries several strategies to extract a YAML block from an LLM output.
    Returns the YAML text or None.
    """
    if not text:
        return None
    # 1) triple-backtick yaml block
    m = re.search(r"```yaml\s*(.+?)\s*```", text, flags=re.S | re.I)
    if m:
        return m.group(1).strip()
    # 2) triple-backtick block without "yaml"
    m = re.search(r"```(.+?)```", text, flags=re.S)
    if m:
        body = m.group(1).strip()
        # Heuristic: starts with 'agents:' or 'tasks:'
        if body.lstrip().startswith(("agents:", "tasks:")):
            return body
    # 3) raw YAML starting at first 'agents:' token
    idx = text.find("agents:")
    if idx != -1:
        cand = text[idx:]
        # attempt parse progressively
        return cand
    return None

def parse_plan_yaml(yaml_text: str) -> dict:
    """Parse YAML and perform basic validation."""
    try:
        plan = yaml.safe_load(yaml_text)
    except Exception as e:
        raise ValueError(f"Invalid YAML: {e}")
    if not isinstance(plan, dict) or "agents" not in plan or "tasks" not in plan:
        raise ValueError("Plan YAML must be a dict with top-level keys 'agents' and 'tasks'.")
    # Basic shape checks
    if not isinstance(plan["agents"], list) or not isinstance(plan["tasks"], list):
        raise ValueError("'agents' and 'tasks' must be lists.")
    return plan

# Cell 3 — create LLM wrapper(s) and Planner agent
# Use the LLM you prefer. Example: Gemini via crewai.LLM (if you provided GOOGLE_API_KEY)
default_model = "gemini/gemini-2.5-flash" if GOOGLE_API_KEY else "openai/gpt-4o-mini"
llm_for_agents = LLM(model=default_model, api_key=GOOGLE_API_KEY or OPENAI_API_KEY)

planner_agent = Agent(
    role="Planner",
    goal=(
        "Given a user request, produce a STRICT YAML plan describing:\n"
        "  - agents: list of agent specs (name, role, goal, optional model)\n"
        "  - tasks: list of tasks (id, agent (name), description, expected_output, optional dependencies)\n\n"
        "Constraints:\n"
        "  - Output only valid YAML (no extra chatty text). If you must include text, wrap YAML in ```yaml blocks.\n"
        "  - Keep tasks small and atomic and refer to agents by 'name'."
    ),
    backstory="Experienced project manager. Output concise valid YAML plan only.",
    llm=llm_for_agents,
    verbose=True
)

planner_task = Task(
    description="Create a YAML plan for: {user_request}\n\nProduce only the YAML.",
    expected_output="A YAML plan containing 'agents' and 'tasks'.",
    agent=planner_agent
)

planner_crew = Crew(
    agents=[planner_agent],
    tasks=[planner_task],
    process=Process.sequential,
    verbose=True
)

# Run planner (example request)
user_request = "Build a 3-step scraper: (1) collect top 5 news articles for a topic; (2) extract headlines + summary; (3) produce one-paragraph digest."
planner_result = planner_crew.kickoff({"user_request": user_request})
print("Planner result (raw):")
pprint(planner_result)

# Cell 4 — extract the YAML produced (robustly) and parse it
# The exact shape of planner_result depends on CrewAI version / verbose mode.
planner_text = None
# attempt common keys
if isinstance(planner_result, dict):
    # try a few likely places (examples from different versions)
    for k in ("output", "result", "final_answer", "final_response", "answer"):
        if k in planner_result and isinstance(planner_result[k], str):
            planner_text = planner_result[k]
            break
    # fallback: stringify the whole result
    if planner_text is None:
        planner_text = str(planner_result)

# now extract YAML
yaml_block = extract_yaml_from_text(planner_text)
if not yaml_block:
    print("No YAML found in planner output. Here's the raw text for debugging:")
    print(planner_text)
else:
    try:
        plan = parse_plan_yaml(yaml_block)
        print("Parsed plan:")
        pprint(plan)
    except Exception as e:
        print("Failed to parse plan:", e)
        print("YAML candidate:")
        print(yaml_block)
        raise

# Cell 5 — fallback/demo plan (use this if planner fails to produce valid YAML)
FALLBACK_PLAN = """
agents:
  - name: researcher
    role: Researcher
    goal: "Collect top-5 news article URLs and short extracts for the given topic."
    model: "gemini/gemini-2.5-flash"
  - name: extractor
    role: Extractor
    goal: "From article URLs, extract headline and 2-sentence summary from each page."
    model: "gemini/gemini-2.5-flash"
  - name: summarizer
    role: Summarizer
    goal: "Produce a one-paragraph digest based on extracted headlines and summaries."
    model: "gemini/gemini-2.5-flash"

tasks:
  - id: t1
    agent: researcher
    description: "Search web for top 5 articles on {topic} and return list of URLs + one-sentence title each."
    expected_output: "List[ {url: str, title: str} ]"
  - id: t2
    agent: extractor
    description: "Fetch each URL from t1 and extract headline and 2-sentence summary."
    expected_output: "List[{url, headline, summary}]"
  - id: t3
    agent: summarizer
    description: "Create a one-paragraph digest from t2 outputs."
    expected_output: "One paragraph"
"""
# Use fallback if plan variable doesn't exist
if 'plan' not in globals():
    plan = parse_plan_yaml(FALLBACK_PLAN)
    print("Using FALLBACK_PLAN (parsed):")
    pprint(plan)

# Cell 6 — instantiate Agents + Tasks for executor crew
# map plan agents to actual crewai.Agent objects
agent_map = {}
default_llm = llm_for_agents  # reuse planner LLM (customize per agent if model field present)

for a in plan["agents"]:
    name = a.get("name")
    model_key = a.get("model")
    model_llm = default_llm
    if model_key:
        # create a per-agent LLM if a different model is requested (use same key)
        model_llm = LLM(model=a.get("model"), api_key=(GOOGLE_API_KEY or OPENAI_API_KEY))
    agent_obj = Agent(
        role=a.get("role", name),
        goal=a.get("goal", ""),
        backstory=a.get("backstory", ""),
        llm=model_llm,
        verbose=True
    )
    agent_map[name] = agent_obj

# create Task objects in the order listed (simple sequential runner)
task_objs = []
for t in plan["tasks"]:
    agent_name = t["agent"]
    if agent_name not in agent_map:
        raise ValueError(f"Agent named '{agent_name}' not defined in plan agents.")
    task_objs.append(Task(
        description=t["description"].format(topic="AI regulation"),
        expected_output=t.get("expected_output", ""),
        agent=agent_map[agent_name]
    ))

# Build the executor crew
executor_crew = Crew(
    agents=list(agent_map.values()),
    tasks=task_objs,
    process=Process.sequential,
    verbose=True
)

# Human-in-the-loop gating: ask user for permission before executing (recommended)
do_execute = True   # change to False to skip
if do_execute:
    print("Running executor crew...")
    exec_result = executor_crew.kickoff({"topic": "AI ethics"})  # provide contextual variables used in tasks
    print("Executor result (raw):")
    pprint(exec_result)
else:
    print("Execution skipped. Inspect 'plan' and agent/task definitions before running.")