# -*- coding: utf-8 -*-
"""Product_recommendation_assistent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGggAKIwAKuVm27vMex0bTk8ET5qIDay
"""

# Install required packages
!pip install openai crewai

import os

# Set your Google AI Studio API Key
os.environ["GOOGLE_API_KEY"] = "AIzaSyBkJsQB6tqzf1r-sKj6lObsf1L5erg-yXM"

products = [
    {"id": 1, "name": "Canon EOS 1500D", "brand": "Canon", "price": 45000, "zoom": 3},
    {"id": 2, "name": "Nikon D3500", "brand": "Nikon", "price": 50000, "zoom": 4},
    {"id": 3, "name": "Sony Alpha A6000", "brand": "Sony", "price": 60000, "zoom": 5},
    {"id": 4, "name": "Canon EOS 90D", "brand": "Canon", "price": 90000, "zoom": 10},
]

class ProductSearchTool:
    def search(self, query=None):
        # Simple search by brand or name
        if query:
            return [p for p in products if query.lower() in p["name"].lower() or query.lower() in p["brand"].lower()]
        return products

class PriceFilterTool:
    def filter_by_price(self, items, min_price=None, max_price=None):
        filtered = items
        if min_price:
            filtered = [p for p in filtered if p["price"] >= min_price]
        if max_price:
            filtered = [p for p in filtered if p["price"] <= max_price]
        return filtered

class DataExtractionAgent:
    def __init__(self, tool):
        self.tool = tool

    def extract(self, query=None):
        return self.tool.search(query)

class FilteringAgent:
    def __init__(self, tool):
        self.tool = tool

    def apply_filters(self, items, min_price=None, max_price=None):
        return self.tool.filter_by_price(items, min_price, max_price)

class RecommendationAgent:
    def recommend(self, items, top_n=3):
        # Simple ranking by price (low to high)
        sorted_items = sorted(items, key=lambda x: x["price"])
        return sorted_items[:top_n]

    def summarize(self, items):
        summary = "Recommended Products:\n"
        for p in items:
            summary += f"- {p['name']} by {p['brand']} at ₹{p['price']}, Zoom: {p['zoom']}x\n"
        return summary

# Function to parse query (basic parsing for demo)
def parse_query(user_query):
    query = None
    min_price = None
    max_price = None

    if "canon" in user_query.lower():
        query = "Canon"
    elif "sony" in user_query.lower():
        query = "Sony"
    elif "nikon" in user_query.lower():
        query = "Nikon"

    import re
    prices = re.findall(r'\d+', user_query.replace(',', ''))
    if "under" in user_query.lower() and prices:
        max_price = int(prices[0])
    if "above" in user_query.lower() and prices:
        min_price = int(prices[0])
    if "between" in user_query.lower() and len(prices) >= 2:
        min_price = int(prices[0])
        max_price = int(prices[1])

    return query, min_price, max_price

# Example: input from user
user_query = input("Enter your query: ")  # e.g., "Canon cameras under 80000"

# Parse the query
query, min_price, max_price = parse_query(user_query)

# Instantiate agents
product_search_tool = ProductSearchTool()
price_filter_tool = PriceFilterTool()
data_agent = DataExtractionAgent(product_search_tool)
filter_agent = FilteringAgent(price_filter_tool)
recommend_agent = RecommendationAgent()


# Step 1: Extract products
extracted = data_agent.extract(query)

# Step 2: Apply filters
filtered = filter_agent.apply_filters(extracted, min_price, max_price)

# Step 3: Recommend
top_products = recommend_agent.recommend(filtered, top_n=3)

# Step 4: Summarize
print(recommend_agent.summarize(top_products))

