# -*- coding: utf-8 -*-
"""LinkedIn_CaptionGenerater.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASutjvDxSs_0sAvcJvYavrNv0B9Pg0Lv
"""

!pip install --upgrade pip
!pip install langchain langchain-google-genai gradio

import os
from getpass import getpass

os.environ["GOOGLE_API_KEY"] = getpass("Enter your Google API key: ")

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import PromptTemplate
from langchain.output_parsers import StructuredOutputParser, ResponseSchema
from langchain.chains import LLMChain
import gradio as gr

response_schemas = [
    ResponseSchema(name="short", description="1-2 sentence punchy LinkedIn post with emojis"),
    ResponseSchema(name="long", description="3-6 sentence detailed LinkedIn post with emojis"),
    ResponseSchema(name="hashtags", description="List of hashtags relevant to the project"),
    ResponseSchema(name="cta", description="One-sentence call to action with emoji if appropriate")
]

output_parser = StructuredOutputParser.from_response_schemas(response_schemas)
format_instructions = output_parser.get_format_instructions()

template = """
You are an expert LinkedIn content writer.
Generate a LinkedIn post description based on the project details.
Make the text engaging, professional, and add relevant emojis 🌟🚀💡 (do not overuse).

Project: {project}
Tone: {tone}
Length_hint: {length}
Include_hashtags: {include_hashtags}

{format_instructions}
"""

prompt = PromptTemplate(
    input_variables=["project", "tone", "length", "include_hashtags"],
    partial_variables={"format_instructions": format_instructions},
    template=template
)

llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",   # ✅ valid model
    temperature=0.7,
    max_output_tokens=500
)

chain = LLMChain(llm=llm, prompt=prompt)

def generate_linkedin_post(project: str, tone="professional", length="short", include_hashtags=True):
    inputs = {
        "project": project,
        "tone": tone,
        "length": length,
        "include_hashtags": "yes" if include_hashtags else "no"
    }

    raw = chain.invoke(inputs)

    try:
        return output_parser.parse(raw["text"])
    except Exception as e:
        return {"error": str(e), "raw": raw}

import gradio as gr

def gr_fn(project, tone, length, hashtags):
    result = generate_linkedin_post(project, tone, length, hashtags)
    if "error" in result:
        return result.get("raw", str(result))

    return f"SHORT:\n{result['short']}\n\nLONG:\n{result['long']}\n\nHASHTAGS:\n{' '.join(result['hashtags'])}\n\nCTA:\n{result['cta']}"

demo = gr.Interface(
    fn=gr_fn,
    inputs=[
        gr.Textbox(lines=5, placeholder="Paste your project description here", label="Project"),
        gr.Dropdown(["professional","casual","celebratory","educational"], value="professional", label="Tone"),
        gr.Dropdown(["short","medium","long"], value="short", label="Length hint"),
        gr.Checkbox(value=True, label="Include hashtags")
    ],
    outputs=gr.Textbox(lines=25, placeholder="Generated LinkedIn post will appear here...", label="Generated Post"),  # ✅ larger output box
    title="LinkedIn Caption Generator (LangChain + Gemini 2.0 Flash + Emojis)"
)

demo.launch(share=True)

