# -*- coding: utf-8 -*-
"""codegen_simple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13e7o5yDEAfHvVKrW6GKuBx6xPfzUrNfS
"""

!pip install boto3
!pip install ruff
!pip install bandit
!pip install mypy

import boto3
import json
import tempfile
import subprocess

# ---- AWS Bedrock direct credentials ----
AWS_ACCESS_KEY = "AKIAVSX4Z23PH4R4CRWQ"
AWS_SECRET_KEY = "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"
AWS_REGION = "us-east-1"  # region where Claude 3 Sonnet is available
MODEL_ID = "anthropic.claude-3-sonnet-20240229-v1:0"

# ---- Prompt template ----
FEW_SHOT_TEMPLATE = """
You are a professional Python developer. Implement functions according to the spec. Examples show desired style.

Example 1:
Spec: Create function add(a:int,b:int)->int that returns a+b.
Code:
def add(a: int, b: int) -> int:
    \"\"\"Return sum of a and b.\"\"\"
    return a + b

Now implement:
Spec:
{spec_text}

Code:
""".strip()

# ---- Invoke Bedrock model ----
def invoke_model(prompt: str) -> str:
    rt = boto3.client(
        "bedrock-runtime",
        region_name=AWS_REGION,
        aws_access_key_id=AWS_ACCESS_KEY,
        aws_secret_access_key=AWS_SECRET_KEY
    )
    body = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 800,
        "temperature": 0.2,
        "messages": [{"role": "user", "content": prompt}],
    }
    resp = rt.invoke_model(
        modelId=MODEL_ID,
        body=json.dumps(body),
        contentType="application/json"
    )
    obj = json.loads(resp["body"].read())
    if "content" in obj and len(obj["content"]) > 0:
        return obj["content"][0].get("text", "")
    return ""

# ---- Generate code ----
def generate_code(spec_text: str):
    prompt = FEW_SHOT_TEMPLATE.format(spec_text=spec_text)
    code_text = invoke_model(prompt)
    # remove code fences
    if code_text.startswith("```"):
        code_text = code_text.strip("```").strip()
    return code_text

# ---- Optionally run static checks ----
def run_linters(code_path: str):
    results = {}
    results["ruff"] = subprocess.run(["ruff", code_path], capture_output=True, text=True)
    results["bandit"] = subprocess.run(["bandit", "-r", code_path], capture_output=True, text=True)
    results["mypy"] = subprocess.run(["mypy", code_path], capture_output=True, text=True)
    return results

# ---- Main ----
if __name__ == "__main__":
    spec = "Write a Python function def factorial(n:int)->int that returns factorial of n (n>=0). Raise ValueError if n<0."
    code = generate_code(spec)

    # Save code to a temporary file
    tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".py")
    tmp_file.write(code.encode("utf-8"))
    tmp_file.close()

    print("=== Generated Code ===")
    print(code)

    # Run lint/security checks
    lint_results = run_linters(tmp_file.name)
    print("\n=== Lint / Security Checks ===")
    for tool, result in lint_results.items():
        print(f"--- {tool} ---")
        print(result.stdout)
        print(result.stderr)