# -*- coding: utf-8 -*-
"""Semantic_Planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsBkLL6A8KPVhMX14VpXBj2_lzzToXbx
"""

!pip install langchain

!pip install -q google-generativeai langchain

import google.generativeai as genai
import os

os.environ["GOOGLE_API_KEY"] = "AIzaSyDvmXzyjXOHipKFddCzIUXpCWBFIb68fH0"


genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

model = genai.GenerativeModel("gemini-2.5-flash")

import json

def semantic_plan(goal: str):
    prompt = f"""
You are an intelligent task planner. Decompose the following goal into a clear, ordered list of subtasks.
Each subtask should be actionable, specific, and logically sequenced.


Goal: {goal}


Return the plan in numbered steps.
"""
    response = model.generate_content(prompt)
    return response.text.strip()

def parse_plan(plan_text: str):
    tasks = []
    for line in plan_text.split("\n"):
        if line.strip() and line[0].isdigit():
            tasks.append(line[line.find('.')+1:].strip())
    return tasks

class TaskExecutor:
    def __init__(self):
        self.context = {}

    def execute(self, task):
        print(f"🧩 Executing: {task}")
        # Placeholder execution logic
        result = f"Completed: {task}"
        self.context[task] = result
        return result

def run_semantic_planner(goal: str):
    display(Markdown(f"### 🎯 **Goal:** {goal}"))
    print("───────────────────────────────────────────────")

    # Generate plan using Gemini
    plan_text = semantic_plan(goal)
    display(Markdown("#### 🗒️ **Generated Plan:**"))
    display(Markdown(f"```\n{plan_text}\n```"))

    # Parse into structured list
    tasks = parse_plan(plan_text)
    executor = TaskExecutor()

    print("\n───────────────────────────────────────────────")
    display(Markdown("#### 🚀 **Executing Tasks Sequentially:**"))
    print("───────────────────────────────────────────────\n")

    for i, task in enumerate(tasks, start=1):
        print(f"Step {i:<2} | 🧩 {task}")
        result = executor.execute(task)
        print(f"        ↳ ✅ {result}\n")

    print("───────────────────────────────────────────────")
    display(Markdown("### ✅ **All Tasks Completed Successfully!**"))

run_semantic_planner("Prepare a weekly marketing report and send it to the manager")





