# -*- coding: utf-8 -*-
"""Autogen_multiagent_research.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mqud039j4PDSbTWs2pbQ9fBu8se4LNaJ
"""

!pip install --upgrade pip
!pip install "pyautogen>=0.2.0"
!pip install "autogen-agentchat>=0.2.0"

!pip install autogen

import autogen
from autogen import ConversableAgent, GroupChat, GroupChatManager, UserProxyAgent, AssistantAgent
print("✅ AutoGen imported successfully")

import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyDvmXzyjXOHipKFddCzIUXpCWBFIb68fH0"

GeminiLLM().complete("Hello")

import google.generativeai as genai
from autogen import AssistantAgent, UserProxyAgent, GroupChat, GroupChatManager
import os

# Configure Gemini
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

# Define a lightweight "LLM function" AutoGen can call
def gemini_llm(prompt: str):
    model = genai.GenerativeModel("gemini-2.5-flash")
    response = model.generate_content(prompt)
    return response.text

class GeminiAssistant(AssistantAgent):
    def generate_reply(self, messages):
        # Extract the conversation as plain text
        prompt = "\n".join([f"{m['role']}: {m['content']}" for m in messages])
        reply = gemini_llm(prompt)
        return reply

planner = GeminiAssistant(
    name="Planner",
    system_message="Plan step-by-step strategies for research tasks."
)

scientist = GeminiAssistant(
    name="Scientist",
    system_message="Analyze data, reason about findings, and generate insights."
)

critic = GeminiAssistant(
    name="Critic",
    system_message="Critically review ideas, point out flaws, and suggest improvements."
)

user = UserProxyAgent(
    name="Researcher",
    system_message="Start and oversee the research discussion."
)

groupchat = GroupChat(
    agents=[user, planner, scientist, critic],
    messages=[],
    max_round=10
)

manager = GroupChatManager(groupchat=groupchat)

speaker_sequence = [planner, scientist, critic]
current_index = 0

def next_speaker():
    global current_index
    speaker = speaker_sequence[current_index]
    current_index = (current_index + 1) % len(speaker_sequence)
    return speaker

from IPython.display import display, HTML

def display_message(role, message):
    colors = {
        "Planner": "#FFD700",   # gold
        "Scientist": "#90EE90", # light green
        "Critic": "#FF6347",    # tomato red
        "Researcher": "#87CEFA" # light blue
    }
    color = colors.get(role, "#D3D3D3")  # default light gray
    html_content = f"""
    <div style="
        border:2px solid {color};
        border-radius:10px;
        padding:10px;
        margin:10px 0;              /* more vertical spacing */
        background-color:{color}33;  /* 20% opacity */
        font-family:Arial, sans-serif;
        line-height:1.5;            /* adds space between lines */
        white-space: pre-wrap;      /* preserves newlines */
    ">
        <b>{role}:</b><br>{message.replace("\n", "<br>")}
    </div>
    """
    display(HTML(html_content))

# Initialize with research topic
initial_message = """Research topic: Self-supervised learning for robot navigation.
Discuss recent progress, propose an experiment, and outline evaluation metrics."""
groupchat.messages.append({"role": "Researcher", "content": initial_message})
display_message("Researcher", initial_message)

# Run multi-agent conversation
for i in range(6):  # 6 rounds total
    speaker = next_speaker()
    reply = speaker.generate_reply(groupchat.messages)
    groupchat.messages.append({"role": speaker.name, "content": reply})
    display_message(speaker.name, reply)